### ISSUE TITLE
ModuleNotFoundError: No module named 'easytorch'

### ISSUE THREAD

**Issue by shuqincao** [GestaltCogTeam/STID#22]
ModuleNotFoundError: No module named 'easytorch'怎么解决呢？
用pip install easytorch时报错

C:\Users>pip install easytorch
Collecting easytorch
  Using cached easytorch-3.8.5.tar.gz (34 kB)
    ERROR: Command errored out with exit status 1:
     command: 'D:\programfiles\anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\wd\\AppData\\Local\\Temp\\pip-install-y5jdlgli\\easytorch\\setup.py'"'"'; __file__='"'"'C:\\Users\\wd\\AppData\\Local\\Temp\\pip-install-y5jdlgli\\easytorch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\wd\AppData\Local\Temp\pip-install-y5jdlgli\easytorch\pip-egg-info'
         cwd: C:\Users\wd\AppData\Local\Temp\pip-install-y5jdlgli\easytorch\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\wd\AppData\Local\Temp\pip-install-y5jdlgli\easytorch\setup.py", line 10, in <module>
        _README = (_HERE / "README.md").read_text()
      File "D:\programfiles\anaconda3\lib\pathlib.py", line 1217, in read_text
        return f.read()
    UnicodeDecodeError: 'gbk' codec can't decode byte 0x85 in position 142: illegal multibyte sequence
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by zezhishao** [comment]
感谢您的Issue，这个仓库有点老，晚点我更新一下。您可以直接用BasicTS那个仓库，那里也可以运行STID，数据集和Baseline都更多。

**Comment by xielingxiwuster** [comment]
我也出现了同样的问题，我是在代码刚刚运行是出现这个报错

**Comment by zhao1840** [comment]
想请问一下，这个是在gpu上运行，我想用cpu版本的torch应该怎么修改呢
